name: Pull request
on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 11
        cache: sbt
    - uses: sbt/setup-sbt@v1
    - name: Compile
      run: sbt +compile
    - name: Run tests
      run: sbt +test
    - name: Run checks
      run: sbt check
